ctools.relationship:
  type: mapping
  label: 'Relationship'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'

condition.plugin.entity_type:*:
  type: condition.plugin
  mapping:
    bundles:
      type: sequence
      sequence:
        type: string
